[character]
success_symbol = '[➜](bold green)'
error_symbol = '[✗](bold red) '

[directory]
use_os_path_sep = false
truncation_symbole = '../'
truncation_length = 2
style = 'bold purple'
before_repo_root_style = 'purple'
repo_root_style = 'bold purple'

[line_break]
disabled = true 

[username]
show_always = true

[aws]
disabled = true

[azure]
disabled = true

[buf]
disabled = true

[bun]
disabled = true

[C]
disabled = true

[CPP]
disabled = true

[CMake]
disabled = true

[COBOL]
disabled = true

[cmd_duration]
disabled = true

[conda]
disabled = true

[container]
disabled = true

[crystal]
disabled = true

[daml]
disabled = true

[dart]
disabled = true

[deno]
disabled = true

[direnv]
disabled = true

[docker_context]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[env_var]
disabled = true

[erlang]
disabled = true

[fennel]
disabled = true

[fill]
disabled = true

[fossil_branch]
disabled = true

[fossil_metrics]
disabled = true

[gcloud]
disabled = true

[git_branch]
disabled = false

[git_commit]
disabled = false

[git_state]
disabled = false

[git_metrics]
disabled = false

[git_status]
disabled = false

[gleam]
disabled = true

[golang]
disabled = true

[guix_shell]
disabled = true

[gradle]
disabled = true

[haskell]
disabled = true

[haxe]
disabled = true

[helm]
disabled = true

[hostname]
disabled = true

[java]
disabled = true

[jobs]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[kubernetes]
disabled = true

[localip]
disabled = true

[lua]
disabled = true

[memory_usage]
disabled = true

[meson]
disabled = true

[hg_branch]
disabled = true

[mise]
disabled = true

[mojo]
disabled = true

[nats]
disabled = true

[netns]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[nodejs]
disabled = true

[ocaml]
disabled = true

[odin]
disabled = true

[opa]
disabled = true

[openstack]
disabled = true

[os]
disabled = true

[package]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[pijul_channel]
disabled = true

[pixi]
disabled = true

[pulumi]
disabled = true

[purescript]
disabled = true

[python]
disabled = true

[quarto]
disabled = true

[rlang]
disabled = true

[raku]
disabled = true

[red]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[scala]
disabled = true

[shell]
disabled = true

[shlvl]
disabled = true

[singularity]
disabled = true

[solidity]
disabled = true

[spack]
disabled = true

[status]
disabled = true

[sudo]
disabled = true

[swift]
disabled = true

[terraform]
disabled = true

[time]
disabled = true

[typst]
disabled = true

[vagrant]
disabled = true

[vlang]
disabled = true

[vcsh]
disabled = true

[zig]
disabled = true
