[metadata]
name = "Cyberpurple"
[colors]
foreground = "#b7b7bd"

selection_fg = 'hsl(0, 100%, 100%)'
# selection_bg = "rgba(125, 38, 135, 0.5)"
selection_bg = 'hsl(300, 100%, 60%)'
cursor_bg = 'hsl(270, 100%, 55%)'
cursor_fg = 'hsl(0, 100%, 100%)'
split = 'hsl(270, 100%, 55%)'
ansi = [
  "#8c1aff",
  "#800000",
  "#00b31e",
  "#b34a00",
  "#8c1aff",
  "#ff33ff",
  "#ff33ff",
  "#8c1aff"
]
brights = [
  "#8c1aff",
  "#800000",
  "#00b31e",
  "#b34a00",
  "#8c1aff",
  "#ff33ff",
  "#ff33ff",
  "#8c1aff"
]
