[metadata]
name = "Cyberpurple"
[colors]
foreground = "#b7b7bd"

selection_fg = 'rgba(255, 255, 255, 1)'
# selection_bg = "rgba(125, 38, 135, 0.5)"
selection_bg = "rgba(0, 0, 0, 0.5)"
cursor_bg = "rgba(125, 38, 135, 1)"
cursor_fb = "rgba(255, 255, 255, 1)"
compose_cursor = "#ae27b1"

split = "rgba(174, 39, 178, 1)"
